### ISSUE TITLE
Message: AADSTS700016: Application with identifier '63890e31-65af-45a3-a3d5-9c52245496aa' was not found in the directory 'Default Directory'.

### ISSUE THREAD

**Issue by VirajKheni** [Azure-Samples/azure-health-data-services-samples#100]
Error occured while testing **Standalone Launch With Patient Scope** (g)(10) Standardized API **1.1.3**

Request Id: ffa7696f-5efb-44ad-8fd8-d3c6e7c04900
Correlation Id: 41dbb355-5553-4793-988e-026f8e1a1cf3
Timestamp: 2023-07-14T04:03:09Z
Message: AADSTS700016: Application with identifier '63890e31-65af-45a3-a3d5-9c52245496aa' was not found in the directory 'Default Directory'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

**If anyone is familiar with this issue or knows how to resolve it, I would greatly appreciate your assistance.**

**Comment by EXPEkesheth** [comment]
Thanks for reporting the issue @VirajKheni - this error is seen if you have app registered in different tenant than FHIR server . If your app is registered in the same tenant, please check your client id to ensure it is correct when initiating a standalone launch

**Comment by VirajKheni** [comment]
Thanks for your assistance it is resolved.
