### ISSUE TITLE
How to add the role FHIR SMART User to the test user

### ISSUE THREAD

**Issue by nimesh13** [Azure-Samples/azure-health-data-services-samples#109]
Hi,

I am following the sample deployment mentioned in this doc: https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/deployment.md

I don't understand how to add the FHIR SMART User role to the test user I created as mentioned in point 2 of this document: https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/patientandpopulationservices-smartonfhir-oncg10/docs/ad-apps/set-fhir-user-mapping.md

Do I assign this user to the app I created?

**Comment by VirajKheni** [comment]
Hello @nimesh13 

You need to assign the FHIR SMART User role to the test user on the FHIR Service in your Health Data Service Workspace.

**Comment by EXPEkesheth** [comment]
@nimesh13 - is the issue resolved for you ?

**Comment by nimesh13** [comment]
Yes, closing this issue. Thanks!
