### ISSUE TITLE
Wrong audience during authorization

### ISSUE THREAD

**Issue by muthink** [Azure-Samples/azure-health-data-services-samples#41]
I am getting the following 400 error during the SMART authorization sequence, after submitting my selection of scopes:
Request:
https://azurefhirdev-apim.azure-api.net/smart/authorize?response_type=code&client_id=ed0bd20c-d3dd-46ad-b1f8-cf34a428cdb0&redirect_uri=https://inferno.healthit.gov/suites/custom/smart/redirect&scope=openid+fhirUser+patient.Medication.read+patient.AllergyIntolerance.read+patient.CarePlan.read+patient.CareTeam.read+patient.Condition.read+patient.Device.read+patient.DiagnosticReport.read+patient.DocumentReference.read+patient.Encounter.read+patient.Goal.read+patient.Immunization.read+patient.Location.read+patient.MedicationRequest.read+patient.Observation.read+patient.Organization.read+patient.Patient.read+patient.Practitioner.read+patient.Procedure.read+patient.Provenance.read+patient.PractitionerRole.read&state=3ce4b9fe-a580-4367-80c5-43845ae3cbe1&aud=https://azurefhirdev-apim.azure-api.net/smart&user=true&prompt=consent&login_hint=[redacted]

Response:
{"Name":"AuthorizeInputFilter","Id":"1ab39e49-e640-4671-a6c5-62cedab033b8","IsFatal":true,"Code":400,"Error":null,"ResponseBody":null}

Application insights reports the following Exception, indicating a mismatching audience.
Result: Pipeline AzureFunctionPipeline-4241f96d-17d7-4e10-8b71-6b728ec1ef9b input filter AuthorizeInputFilter-a7034d56-ac30-4e6a-a394-bc9b8b2a9cb2 error.
Exception: System.ArgumentException: Audience does not match configuration. {"ResponseType":"code","ClientId":"ed0bd20c-d3dd-46ad-b1f8-cf34a428cdb0","RedirectUri":"https://inferno.healthit.gov/suites/custom/smart/redirect","Scope":"openid https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/fhirUser offline_access https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Medication.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.AllergyIntolerance.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.CarePlan.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.CareTeam.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Condition.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Device.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.DiagnosticReport.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.DocumentReference.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Encounter.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Goal.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Immunization.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Location.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.MedicationRequest.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Observation.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Organization.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Patient.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Practitioner.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Procedure.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.Provenance.read https://azurefhirdevahds-fhirdata.fhir.azurehealthcareapis.com/patient.PractitionerRole.read","State":"22cff55a-afa1-4491-9d0a-50319d2414b5","Audience":"https://azurefhirdev-apim.azure-api.net/smart","CodeChallenge":null,"CodeChallengeMethod":null,"Prompt":"consent","LoginHint":[redact]}
Stack:

**Comment by EXPEkesheth** [comment]
Thanks for reporting the issue! We are actively looking into resolution. We will respond back with update soon.

**Comment by muthink** [comment]
I can confirm that commit 883d29b fixes this issue.
