### ISSUE TITLE
Inferno g10 SMART auth sequence fails with AADSTS9002325

### ISSUE THREAD

**Issue by muthink** [Azure-Samples/azure-health-data-services-samples#55]
This occurs after approving the scopes and authenticating, which are successful, until this error occurs:
I'll add more diagnostics as I collect anything relevant.
AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption.

![image](https://user-images.githubusercontent.com/1256768/224323438-6f0ea912-478d-4eff-922f-78702e808d8a.png)

**Comment by EXPEkesheth** [comment]
@muthink - did you change the application setting from web to SPA? Changing the setting can help, please let us know if this fixes the issue you are facing. Thanks!

**Comment by muthink** [comment]
Yes, it was SPA

**Comment by mikaelweave** [comment]
Can you redeploy from main? A couple changes have been made since the issue was submitted:
- Function Apps run on Linux now in consumption mode. Cheaper, less quota issues.
- PKCE fix fully fleshed out
    -This has to do with the origin header always being there (which AAD did not like.). I think your latest ticket still uses the older code.
- Better docs about seeding with US Core and test data

**Comment by EXPEkesheth** [comment]
@muthink - can we close this issue?
