### ISSUE TITLE
Inferno Test 9.1 Failing

### ISSUE THREAD

**Issue by yoju0121** [Azure-Samples/azure-health-data-services-samples#69]
Inferno 9.1 Public Client test is failing, namely 9.1.05. POST /token is returning a 401, citing the following error message.

Erik found out that the bug is [here](https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/samples/Patient%20and%20Population%20Services%20G10/src/SMARTCustomOperations.AzureAuth/Models/TokenContext.cs#L42); not only do we need to check if `client_secret` key is present, it should also be checked to see if the field has a value before creating the `ConfidentialClientTokenContext`.

With this change in the code, we won't be needing a separate app registration for public client.

**Comment by EXPEkesheth** [comment]
Fixed
