### ISSUE TITLE
Link to SMART g(10) sample throws 404 error

### ISSUE THREAD

**Issue by erikhoward** [Azure-Samples/azure-health-data-services-samples#85]
The [link](https://github.com/Azure-Samples/azure-health-data-services-samples/tree/main/samples/Patient%20and%20Population%20Services%20G10) to the SMART ONC g(10) sample is throwing a 404 error. The link needs to be updated to match the recent renaming of the SMART samples folder.

**Comment by EXPEkesheth** [comment]
@erikhoward - where is the link posted in the document? If i can get the link, will be able to correct.

**Comment by erikhoward** [comment]
@EXPEkesheth The link to the SMART sample in the main [README.md](https://github.com/Azure-Samples/azure-health-data-services-samples/blob/main/README.md) file was wrong. Just checked and it seems to have been resolved in a previous PR. This issue can be closed.
